In [1]:
import torch
inputs = torch.tensor(
   [[0.1, 0.9, 0.2],  # <- Вектор для ID=101 ("Hello,") 
    [0.8, 0.1, 0.1],  # <- Вектор для ID=102 ("world.")
    [0.3, 0.2, 0.9],  # <- Вектор для ID=103 ("This")
    [0.4, 0.8, 0.3],  # <- Вектор для ID=104 ("is")
    [0.9, 0.1, 0.1],  # <- Вектор для ID=105 ("a")
    [0.2, 0.3, 0.8]]  # <- Вектор для ID=106 ("test.")    
)
query = inputs[1]
attn_score_2 = torch.empty(inputs.shape[0])
for i, x_i in enumerate(inputs):
    attn_score_2[i] = torch.dot(x_i, query)
print(attn_score_2)

tensor([0.1900, 0.6600, 0.3500, 0.4300, 0.7400, 0.2700])


In [2]:
res = 0.
for idx, element in enumerate(inputs[0]):
    res += inputs[0][idx] * query[idx]
print(res)                    # tensor(0.1900)

tensor(0.1900)


In [3]:
#ttn_weights_2_tmp = attn_score_2 / attn_score_2.sum()
#print("Веса внимания:", attn_weights_2_tmp)
#print("Сумма:", attn_weights_2_tmp.sum())

In [4]:
attn_weights_2_tmp = attn_score_2 / attn_score_2.sum()
def softmax_naive(x):
    return torch.exp(x)/torch.exp(x).sum(dim=0)

attn_weights_2_naive = softmax_naive(attn_score_2)
print("Attention weights:", attn_weights_2_naive)
print("Sum:", attn_weights_2_naive.sum())

Attention weights: tensor([0.1272, 0.2035, 0.1493, 0.1617, 0.2205, 0.1378])
Sum: tensor(1.0000)


In [5]:
def softmax_naive(x):
    return torch.exp(x)/torch.exp(x).sum(dim=0)

attn_weights_2_naive = softmax_naive(attn_score_2)
print("Attention weights:", attn_weights_2_naive)
print("Sum:", attn_weights_2_naive.sum())

attn_weights_2 = torch.softmax(attn_score_2, dim=0)
print("Attention weights:", attn_weights_2)
print("Sum:", attn_weights_2.sum())

Attention weights: tensor([0.1272, 0.2035, 0.1493, 0.1617, 0.2205, 0.1378])
Sum: tensor(1.0000)
Attention weights: tensor([0.1272, 0.2035, 0.1493, 0.1617, 0.2205, 0.1378])
Sum: tensor(1.0000)


In [6]:
attn_weights_2 = torch.softmax(attn_score_2, dim=0)
print("Attention weights:", attn_weights_2)
print("Sum:", attn_weights_2.sum())

Attention weights: tensor([0.1272, 0.2035, 0.1493, 0.1617, 0.2205, 0.1378])
Sum: tensor(1.0000)


In [7]:
query = inputs[1]
context_vec_2 = torch.zeros(query.shape)
for i, x_i in enumerate(inputs):
    context_vec_2 += attn_weights_2[i]*x_i
print(context_vec_2)

tensor([0.5110, 0.3574, 0.3609])


In [8]:
attn_scores = torch.empty(6,6)
for i, x_i in enumerate(inputs):
    for j, x_j in enumerate(inputs):
        attn_scores[i, j] = torch.dot(x_i, x_j)
print(attn_scores)

tensor([[0.8600, 0.1900, 0.3900, 0.8200, 0.2000, 0.4500],
        [0.1900, 0.6600, 0.3500, 0.4300, 0.7400, 0.2700],
        [0.3900, 0.3500, 0.9400, 0.5500, 0.3800, 0.8400],
        [0.8200, 0.4300, 0.5500, 0.8900, 0.4700, 0.5600],
        [0.2000, 0.7400, 0.3800, 0.4700, 0.8300, 0.2900],
        [0.4500, 0.2700, 0.8400, 0.5600, 0.2900, 0.7700]])


In [9]:
attn_scores = inputs @ inputs.T
print(attn_scores)

tensor([[0.8600, 0.1900, 0.3900, 0.8200, 0.2000, 0.4500],
        [0.1900, 0.6600, 0.3500, 0.4300, 0.7400, 0.2700],
        [0.3900, 0.3500, 0.9400, 0.5500, 0.3800, 0.8400],
        [0.8200, 0.4300, 0.5500, 0.8900, 0.4700, 0.5600],
        [0.2000, 0.7400, 0.3800, 0.4700, 0.8300, 0.2900],
        [0.4500, 0.2700, 0.8400, 0.5600, 0.2900, 0.7700]])


In [10]:
attn_weights = torch.softmax(attn_scores, dim=-1)
print(attn_weights)

tensor([[0.2338, 0.1196, 0.1461, 0.2246, 0.1208, 0.1551],
        [0.1272, 0.2035, 0.1493, 0.1617, 0.2205, 0.1378],
        [0.1347, 0.1294, 0.2334, 0.1580, 0.1333, 0.2112],
        [0.2005, 0.1357, 0.1530, 0.2150, 0.1413, 0.1546],
        [0.1220, 0.2094, 0.1461, 0.1598, 0.2291, 0.1335],
        [0.1502, 0.1255, 0.2218, 0.1677, 0.1280, 0.2068]])


In [11]:
row_2_sum = sum([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
print("Row 2 sum:", row_2_sum)
print("All row sums:", attn_weights.sum(dim=-1))

Row 2 sum: 1.0
All row sums: tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])


In [12]:
all_context_vecs = attn_weights @ inputs
print(all_context_vecs)

tensor([[0.3925, 0.4899, 0.3938],
        [0.5110, 0.3574, 0.3609],
        [0.4124, 0.3839, 0.4796],
        [0.4186, 0.4571, 0.3937],
        [0.5204, 0.3508, 0.3545],
        [0.4056, 0.4011, 0.4708]])


In [13]:
x_2 = inputs[1]
d_in = inputs.shape[1]
d_out = 2
torch.manual_seed(123)
W_query = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_key   = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_value = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
print(W_query)
print(W_key)
print(W_value)
print(inputs)
print(x_2)

Parameter containing:
tensor([[0.2961, 0.5166],
        [0.2517, 0.6886],
        [0.0740, 0.8665]])
Parameter containing:
tensor([[0.1366, 0.1025],
        [0.1841, 0.7264],
        [0.3153, 0.6871]])
Parameter containing:
tensor([[0.0756, 0.1966],
        [0.3164, 0.4017],
        [0.1186, 0.8274]])
tensor([[0.1000, 0.9000, 0.2000],
        [0.8000, 0.1000, 0.1000],
        [0.3000, 0.2000, 0.9000],
        [0.4000, 0.8000, 0.3000],
        [0.9000, 0.1000, 0.1000],
        [0.2000, 0.3000, 0.8000]])
tensor([0.8000, 0.1000, 0.1000])


In [14]:
query_2 = x_2 @ W_query
key_2   = x_2 @ W_key
value_2 = x_2 @ W_value
print(query_2)
print(key_2)
print(value_2)

tensor([0.2695, 0.5688])
tensor([0.1592, 0.2233])
tensor([0.1040, 0.2802])


In [15]:
keys   = inputs @ W_key
values = inputs @ W_value
print("keys.shape:", keys.shape)
print("values.shape:", values.shape)
print(keys)
print(values)

keys.shape: torch.Size([6, 2])
values.shape: torch.Size([6, 2])
tensor([[0.2424, 0.8015],
        [0.1592, 0.2233],
        [0.3615, 0.7944],
        [0.2965, 0.8283],
        [0.1729, 0.2336],
        [0.3347, 0.7881]])
tensor([[0.3160, 0.5467],
        [0.1040, 0.2802],
        [0.1927, 0.8840],
        [0.3190, 0.6483],
        [0.1116, 0.2999],
        [0.2049, 0.8218]])


In [16]:
keys_2 = keys[1]
attn_score_22 = query_2.dot(keys_2)
print(attn_score_22)

tensor(0.1699)


In [17]:
attn_scores_2 = query_2 @ keys.T
print(attn_scores_2)

tensor([0.5211, 0.1699, 0.5492, 0.5510, 0.1794, 0.5384])


In [18]:
d_k = keys.shape[-1]
attn_weights_2 = torch.softmax(attn_scores_2 / d_k**0.5, dim=-1)
print(attn_weights_2)

tensor([0.1780, 0.1388, 0.1815, 0.1818, 0.1398, 0.1802])


In [19]:
context_vec_2 = attn_weights_2 @ values
print(attn_weights_2)
print(values)
print(context_vec_2)

tensor([0.1780, 0.1388, 0.1815, 0.1818, 0.1398, 0.1802])
tensor([[0.3160, 0.5467],
        [0.1040, 0.2802],
        [0.1927, 0.8840],
        [0.3190, 0.6483],
        [0.1116, 0.2999],
        [0.2049, 0.8218]])
tensor([0.2161, 0.6045])


In [20]:
import torch.nn as nn
class SelfAttention_v1(nn.Module):
    def __init__(self, d_in, d_out):
        super().__init__()
        self.W_query = nn.Parameter(torch.rand(d_in, d_out))
        self.W_key   = nn.Parameter(torch.rand(d_in, d_out))
        self.W_value = nn.Parameter(torch.rand(d_in, d_out))

    def forward(self, x):
        keys    = x @ self.W_key
        queries = x @ self.W_query
        values  = x @ self.W_value
        attn_scores = queries @ keys.T # omega
        attn_weights = torch.softmax(attn_scores / keys.shape[-1]**0.5, dim=-1)
        context_vec = attn_weights @ values
        return context_vec

In [21]:
torch.manual_seed(123)
sa_v1 = SelfAttention_v1(d_in, d_out)
print(sa_v1(inputs))

tensor([[0.2195, 0.6139],
        [0.2161, 0.6045],
        [0.2221, 0.6205],
        [0.2217, 0.6203],
        [0.2168, 0.6066],
        [0.2213, 0.6182]], grad_fn=<MmBackward0>)


In [22]:
class SelfAttention_v2(nn.Module):
    def __init__(self, d_in, d_out, qkv_bias=False):
        super().__init__()
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key   = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)

    def forward(self, x):
        keys    = self.W_key(x)
        queries = self.W_query(x)
        values  = self.W_value(x)
        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(attn_scores / keys.shape[-1]**0.5, dim=-1)
        context_vec = attn_weights @ values
        return context_vec

In [23]:
torch.manual_seed(789) #789
sa_v2 = SelfAttention_v2(d_in, d_out)
print(sa_v2(inputs))

tensor([[-0.0210,  0.1178],
        [-0.0201,  0.1194],
        [-0.0161,  0.1250],
        [-0.0202,  0.1190],
        [-0.0200,  0.1195],
        [-0.0169,  0.1239]], grad_fn=<MmBackward0>)


In [24]:
queries = sa_v2.W_query(inputs)
keys = sa_v2.W_key(inputs)
attn_scores = queries @ keys.T
attn_weights = torch.softmax(attn_scores / keys.shape[-1]**0.5, dim=-1)
print("Inputs:", inputs)
print("W_query:", W_query)
print("Queries:", queries)
print("Keys:", keys)
print(attn_weights)

Inputs: tensor([[0.1000, 0.9000, 0.2000],
        [0.8000, 0.1000, 0.1000],
        [0.3000, 0.2000, 0.9000],
        [0.4000, 0.8000, 0.3000],
        [0.9000, 0.1000, 0.1000],
        [0.2000, 0.3000, 0.8000]])
W_query: Parameter containing:
tensor([[0.2961, 0.5166],
        [0.2517, 0.6886],
        [0.0740, 0.8665]])
Queries: tensor([[ 0.5451, -0.3393],
        [ 0.3497, -0.1776],
        [ 0.6468, -0.2007],
        [ 0.6454, -0.3651],
        [ 0.3813, -0.1944],
        [ 0.6097, -0.2084]], grad_fn=<MmBackward0>)
Keys: tensor([[-0.3354, -0.3148],
        [ 0.3013,  0.0936],
        [ 0.2408, -0.4475],
        [-0.1430, -0.2759],
        [ 0.3419,  0.1150],
        [ 0.1295, -0.4438]], grad_fn=<MmBackward0>)
tensor([[0.1445, 0.1675, 0.1863, 0.1542, 0.1692, 0.1783],
        [0.1518, 0.1688, 0.1780, 0.1584, 0.1700, 0.1731],
        [0.1386, 0.1750, 0.1838, 0.1505, 0.1777, 0.1746],
        [0.1403, 0.1688, 0.1889, 0.1516, 0.1710, 0.1793],
        [0.1505, 0.1689, 0.1790, 0.1577, 0.170

In [25]:
real_W_query = sa_v2.W_key.weight.T  # (3, 2)
print(real_W_query)

tensor([[ 0.4058,  0.2134],
        [-0.4704, -0.2601],
        [ 0.2368, -0.5105]], grad_fn=<PermuteBackward0>)


In [26]:
context_length = attn_scores.shape[0]
mask_simple = torch.tril(torch.ones(context_length, context_length))
print(mask_simple)

tensor([[1., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1.]])


In [27]:
masked_simple = attn_weights * mask_simple
print(masked_simple)

tensor([[0.1445, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1518, 0.1688, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1386, 0.1750, 0.1838, 0.0000, 0.0000, 0.0000],
        [0.1403, 0.1688, 0.1889, 0.1516, 0.0000, 0.0000],
        [0.1505, 0.1689, 0.1790, 0.1577, 0.1703, 0.0000],
        [0.1403, 0.1738, 0.1834, 0.1515, 0.1763, 0.1747]],
       grad_fn=<MulBackward0>)


In [28]:
row_sums = masked_simple.sum(dim=-1, keepdim=True)
masked_simple_norm = masked_simple / row_sums
print(masked_simple_norm)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4735, 0.5265, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2786, 0.3518, 0.3695, 0.0000, 0.0000, 0.0000],
        [0.2160, 0.2599, 0.2907, 0.2334, 0.0000, 0.0000],
        [0.1821, 0.2044, 0.2166, 0.1908, 0.2061, 0.0000],
        [0.1403, 0.1738, 0.1834, 0.1515, 0.1763, 0.1747]],
       grad_fn=<DivBackward0>)


In [29]:
mask = torch.triu(torch.ones(context_length, context_length), diagonal=1)
masked = attn_scores.masked_fill(mask.bool(), -torch.inf)
print(masked)

tensor([[-0.0760,    -inf,    -inf,    -inf,    -inf,    -inf],
        [-0.0614,  0.0887,    -inf,    -inf,    -inf,    -inf],
        [-0.1538,  0.1761,  0.2455,    -inf,    -inf,    -inf],
        [-0.1015,  0.1603,  0.3188,  0.0085,    -inf,    -inf],
        [-0.0667,  0.0967,  0.1788, -0.0009,  0.1080,    -inf],
        [-0.1389,  0.1642,  0.2401, -0.0297,  0.1845,  0.1714]],
       grad_fn=<MaskedFillBackward0>)


In [30]:
attn_weights = torch.softmax(masked/keys.shape[-1]**0.5, dim=1)
print(attn_weights)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4735, 0.5265, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2786, 0.3518, 0.3695, 0.0000, 0.0000, 0.0000],
        [0.2160, 0.2599, 0.2907, 0.2334, 0.0000, 0.0000],
        [0.1821, 0.2044, 0.2166, 0.1908, 0.2061, 0.0000],
        [0.1403, 0.1738, 0.1834, 0.1515, 0.1763, 0.1747]],
       grad_fn=<SoftmaxBackward0>)


In [31]:
import torch
torch.manual_seed(123)
dropout = torch.nn.Dropout(0.5)
example = torch.ones(6,6)
print(dropout(example))

tensor([[2., 2., 2., 2., 2., 2.],
        [0., 2., 0., 0., 0., 0.],
        [0., 0., 2., 0., 2., 0.],
        [2., 2., 0., 0., 0., 2.],
        [2., 0., 0., 0., 0., 2.],
        [0., 2., 0., 0., 0., 0.]])


In [32]:
torch.manual_seed(123)
print(dropout(attn_weights))

tensor([[2.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 1.0530, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.7391, 0.0000, 0.0000, 0.0000],
        [0.4319, 0.5198, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3642, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.3476, 0.0000, 0.0000, 0.0000, 0.0000]],
       grad_fn=<MulBackward0>)


In [33]:
batch = torch.stack((inputs, inputs), dim=0)
print(batch.shape)

torch.Size([2, 6, 3])


In [34]:
class CausalAttention(nn.Module):
    def __init__(self, d_in, d_out, context_length, dropout, qkv_bias=False):
        super().__init__()
        self.d_out = d_out
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.dropout = nn.Dropout(dropout)
        self.register_buffer('mask', torch.triu(torch.ones(context_length, context_length), diagonal=1))

    def forward(self, x):
        b, num_tokens, d_in = x.shape
        keys = self.W_key(x)
        queries = self.W_query(x)
        values  = self.W_value(x)

        attn_scores = queries @ keys.transpose(1,2)
        attn_scores.masked_fill_(self.mask.bool()[:num_tokens, :num_tokens], -torch.inf)
        attn_weights = torch.softmax(attn_scores/keys.shape[-1]**0.5, dim=-1)
        attn_weigths = self.dropout(attn_weights)
        context_vec = attn_weights @ values
        return context_vec

In [35]:
torch.manual_seed(123)
context_length = batch.shape[1]
ca = CausalAttention(d_in, d_out, context_length, 0.0)
context_vecs = ca(batch)
print("context_vecs.shape:", context_vecs.shape)

context_vecs.shape: torch.Size([2, 6, 2])


In [72]:
class MultiHeadAttentionWrapper(nn.Module):
    def __init__(self, d_in, d_out, context_length, dropout, num_heads, qkv_bias=False):
        super().__init__()
        self.heads = nn.ModuleList([CausalAttention(d_in, d_out, context_length, dropout, qkv_bias)
            for _ in range(num_heads)])
    def forward(self, x):
        return torch.cat([head(x) for head in self.heads], dim=-1)

In [74]:
torch.manual_seed(123)
context_length = batch.shape[1]
d_in, d_out = 3, 2
mha = MultiHeadAttentionWrapper(d_in, d_out, context_length, 0.0, num_heads=2)
context_vecs = mha(batch)

print(context_vecs)
print("context_vecs.shape:", context_vecs.shape)

tensor([[[-0.4067, -0.3321,  0.3477,  0.4405],
         [-0.4277, -0.2132,  0.3976,  0.3351],
         [-0.4210, -0.0621,  0.4045,  0.2746],
         [-0.4511, -0.1278,  0.4289,  0.3171],
         [-0.4602, -0.1183,  0.4431,  0.2982],
         [-0.4456, -0.0732,  0.4338,  0.2833]],

        [[-0.4067, -0.3321,  0.3477,  0.4405],
         [-0.4277, -0.2132,  0.3976,  0.3351],
         [-0.4210, -0.0621,  0.4045,  0.2746],
         [-0.4511, -0.1278,  0.4289,  0.3171],
         [-0.4602, -0.1183,  0.4431,  0.2982],
         [-0.4456, -0.0732,  0.4338,  0.2833]]], grad_fn=<CatBackward0>)
context_vecs.shape: torch.Size([2, 6, 4])


In [76]:
class MultiHeadAttention(nn.Module):
    def __init__(self, d_in, d_out, context_length, dropout, num_heads, qkv_bias=False):
        super().__init__()
        assert (d_out % num_heads == 0), \
            "d_out must be divisible by num_heads"
        self.d_out = d_out
        self.num_heads = num_heads
        self.head_dim = d_out // num_heads
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.out_proj = nn.Linear(d_out, d_out)
        self.dropout = nn.Dropout(dropout)
        self.register_buffer('mask', torch.triu(torch.ones(context_length, context_length), diagonal=1))

    def forward(self, x):
        b, num_tokens, d_in = x.shape
        keys    = self.W_key(x)
        queries = self.W_query(x)
        values  = self.W_value(x)
        keys    = keys.view(b, num_tokens, self.num_heads, self.head_dim)
        values  = values.view(b, num_tokens, self.num_heads, self.head_dim)
        queries = queries.view(b, num_tokens, self.num_heads, self.head_dim)
        keys    = keys.transpose(1,2)
        values  = values.transpose(1,2)
        queries = queries.transpose(1,2)
        

        attn_scores = queries @ keys.transpose(2,3)
        mask_bool = self.mask.bool()[:num_tokens, :num_tokens]
        attn_scores.masked_fill_(mask_bool, -torch.inf)
        
        attn_weights = torch.softmax(attn_scores/keys.shape[-1]**0.5, dim=-1)
        attn_weigths = self.dropout(attn_weights)
        
        context_vec = (attn_weights @ values).transpose(1,2)
        context_vec = context_vec.contiguous().view(b, num_tokens, self.d_out)
        context_vec = self.out_proj(context_vec)
        return context_vec

In [78]:
a = torch.tensor([[[[0.2745, 0.6584, 0.2775, 0.8573],
    [0.8993, 0.0390, 0.9268, 0.7388],
    [0.7179, 0.7058, 0.9156, 0.4340]],
                   
    [[0.0772, 0.3565, 0.1479, 0.5331],
    [0.4066, 0.2318, 0.4545, 0.9737],
    [0.4606, 0.5159, 0.4220, 0.5786]]]])
print(a@a.transpose(2,3))

tensor([[[[1.3208, 1.1631, 1.2879],
          [1.1631, 2.2150, 1.8424],
          [1.2879, 1.8424, 2.0402]],

         [[0.4391, 0.7003, 0.5903],
          [0.7003, 1.3737, 1.0620],
          [0.5903, 1.0620, 0.9912]]]])


In [80]:
first_head = a[0, 0, :, :]
first_res = first_head @ first_head.T
print("First head:\n", first_res)

second_head = a[0, 1, :, :]
second_res = second_head @ second_head.T
print("\nSecond head:\n", second_res)

First head:
 tensor([[1.3208, 1.1631, 1.2879],
        [1.1631, 2.2150, 1.8424],
        [1.2879, 1.8424, 2.0402]])

Second head:
 tensor([[0.4391, 0.7003, 0.5903],
        [0.7003, 1.3737, 1.0620],
        [0.5903, 1.0620, 0.9912]])


In [82]:
torch.manual_seed(123)
batch_size, context_lehgth, d_in = batch.shape
d_out=2
mha=MultiHeadAttention(d_in, d_out, context_length, 0.0, num_heads=2)
context_vec = mha(batch)
print(context_vec)
print("context_vec.shape:", context_vec.shape)

tensor([[[0.1858, 0.4354],
         [0.2166, 0.4411],
         [0.2499, 0.4644],
         [0.2393, 0.4400],
         [0.2437, 0.4370],
         [0.2515, 0.4503]],

        [[0.1858, 0.4354],
         [0.2166, 0.4411],
         [0.2499, 0.4644],
         [0.2393, 0.4400],
         [0.2437, 0.4370],
         [0.2515, 0.4503]]], grad_fn=<ViewBackward0>)
context_vec.shape: torch.Size([2, 6, 2])
